name: generate and publish manifest

on:
  push:
    tags: ["v*"]

permissions:
  contents: write

jobs:
  release-plugin-and-manifest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Download JSON file
        uses: actions/download-artifact@v4
        with:
          name: manifest
      - name: Compress build files
        uses: thedoctor0/zip-release@0.7.6
        with:
          type: "zip"
          directory: "./"
          filename: "vfox-bun-${{ github.ref_name }}.zip"
          exclusions: "*.git*"
      - name: Publish release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: "vfox-bun-${{ github.ref_name }}.zip"
          tag: "${{ github.ref_name }}"
          file_glob: true
